services:
  # ─── PostgreSQL ───────────────────────────────────────────────
  db:
    image: supabase/postgres:15.8.1.060
    environment:
      POSTGRES_HOST: /var/run/postgresql
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: postgres
      JWT_SECRET: ${JWT_SECRET}
      POSTGRES_HOST_AUTH_METHOD: md5
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -h localhost"]
      interval: 5s
      timeout: 5s
      retries: 10
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.role == manager
  # ─── Supavisor ────────────────────────────────────────────────
  supavisor:
    image: supabase/supavisor:2.5.1
    ports:
      - "6543:6543"
      - "5433:5433"
    environment:
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      DATABASE_URL: "ecto://supabase_admin:${POSTGRES_PASSWORD}@db:5432/postgres"
      CLUSTER_POSTGRES: "true"
      SECRET_KEY_BASE: ${SECRET_KEY_BASE}
      VAULT_ENC_KEY: ${VAULT_ENC_KEY}
      API_JWT_SECRET: ${JWT_SECRET}
      METRICS_JWT_SECRET: ${JWT_SECRET}
      REGION: local
      ERL_AFLAGS: -proto_dist inet_tcp
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  # ─── pg-meta ──────────────────────────────────────────────────
  meta:
    image: supabase/postgres-meta:v0.84.2
    environment:
      PG_META_PORT: 8080
      PG_META_DB_HOST: db
      PG_META_DB_PORT: 5432
      PG_META_DB_NAME: postgres
      PG_META_DB_USER: supabase_admin
      PG_META_DB_PASSWORD: ${POSTGRES_PASSWORD}
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  # ─── Kong Init (gera kong.yml e desliga) ──────────────────────
  kong-init:
    image: alpine:3.19
    environment:
      KONG_ADMIN_USER: ${KONG_ADMIN_USER}
      KONG_ADMIN_PASSWORD: ${KONG_ADMIN_PASSWORD}
    volumes:
      - kong-config:/var/lib/kong
    configs:
      - source: kong_template_v1
        target: /tmp/kong-template.yml
      - source: kong_init_script_v1
        target: /tmp/kong-init.sh
        mode: 0755
    command: sh /tmp/kong-init.sh
    deploy:
      replicas: 1
      restart_policy:
        condition: none

  # ─── Kong (API Gateway) ───────────────────────────────────────
  kong:
    image: kong:2.8.1
    ports:
      - "8000:8000"
    environment:
      KONG_DATABASE: "off"
      KONG_DECLARATIVE_CONFIG: /var/lib/kong/kong.yml
      KONG_DNS_ORDER: LAST,A,CNAME
      KONG_PLUGINS: request-transformer,cors,key-auth,acl,basic-auth
      KONG_NGINX_PROXY_PROXY_BUFFER_SIZE: 160k
      KONG_NGINX_PROXY_PROXY_BUFFERS: 64 160k
    volumes:
      - kong-config:/var/lib/kong
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  # ─── Supabase Studio ──────────────────────────────────────────
  studio:
    image: supabase/studio:20250113-83c9420
    environment:
      STUDIO_PG_META_URL: http://meta:8080
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      DEFAULT_ORGANIZATION_NAME: ${STUDIO_DEFAULT_ORGANIZATION:-Minha Empresa}
      DEFAULT_PROJECT_NAME: ${STUDIO_DEFAULT_PROJECT:-Meu Projeto}
      SUPABASE_URL: http://kong:8000
      SUPABASE_PUBLIC_URL: ${SUPABASE_PUBLIC_URL:-http://localhost:8000}
      SUPABASE_ANON_KEY: ${ANON_KEY}
      SUPABASE_SERVICE_KEY: ${SERVICE_ROLE_KEY}
      AUTH_JWT_SECRET: ${JWT_SECRET}
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

volumes:
  db-data:
    driver: local
  kong-config:
    driver: local

configs:
  kong_template_v1:
    file: ./kong-template.yml
  kong_init_script_v1:
    file: ./kong-init-swarm.sh